# Generated by Django 4.2.23 on 2025-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_date"]},
        ),
        migrations.AddField(
            model_name="post",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
